### ISSUE TITLE
Users should provide their own search credentials for dynamic image search

### ISSUE THREAD

**Issue by Graham-Foster** [annsonn/fancy-carousel#2]
### Description

The element is configured to use a specific custom search engine and is hard coded with a corresponding API key.  This isn't appropriate for other people to use this element
### Expected outcome

Ideally, the user should be providing their own custom search engine and API key
### Browsers Affected
- [X] Chrome
- [X] Firefox
- [X] Safari 10
- [X] Safari 9
- [X] Edge
- [X] IE 11

**Comment by annsonn** [comment]
Fixed as of v1.0.2
